In [81]:
import numpy as np
with open('input.txt', 'r') as f:
    input = f.read()
input = [x for x in input]
count = 0
direction_index = 0
rock_index = 0
rock_patterns = [[[2, 2, 2, 2]], [[0, 2, 0, 0], [2, 2, 2, 0], [0, 2, 0, 0]], [[0, 0, 2, 0], [0, 0, 2, 0], [2, 2, 2, 0]], [[2, 0, 0, 0], [2, 0, 0, 0], [2, 0, 0, 0], [2, 0, 0, 0]], [[2, 2, 0, 0], [2, 2, 0, 0]]]
rock_patterns = np.array([np.array(pattern, dtype="object") for pattern in rock_patterns], dtype="object")
for i, _ in enumerate(rock_patterns):
    rock_patterns[i].resize((4,4), refcheck = False)
cave = np.zeros((3, 7))
current_tallest = 0
y_index = 0
print(rock_patterns[0])
while(True):
    count += 1
    direction_index = (direction_index + 1) % len(input)
    if count > 100:
        break
    x_correction = -1 if input[direction_index] == '<' else 1
    check = len(rock_patterns[rock_index]) + current_tallest + 3 - len(cave)
    if(check >= 0):
        cave = np.append(cave, np.zeros((check, 7)), 0)
    
    # print(cave, check)
    
    
    

[[2 2 2 2]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
